version: '3.8'

networks:
    kong-net:
        name: kong-net
        driver: bridge
services:
    kong-database:
        image: postgres:9.6
        container_name: kong-database
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        ports:
            - "5432:5432"
        volumes:
            - /Users/thanhtk/Work/Documents/Work/PyCorpProj/db-data:/var/lib/postgresql/data
        networks:
            - kong-net 
    
    kong-migrations:
        image: kong:latest
        container_name: kong-migrations
        restart: on-failure
        depends_on:
            - kong-database
        links:
            - kong-database:kong-database
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: kong
            KONG_CASSANDRA_CONTACT_POINTS: kong-database
        entrypoint: sh -c "sleep 100 && kong migrations bootstrap --vv"
        networks:
            - kong-net
            
    kong:
        image: kong:latest
        container_name: kong
        restart: on-failure
        links:
            - kong-database:kong-database
        networks:
            - kong-net
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: kong-database
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: kong
            KONG_CASSANDRA_CONTACT_POINTS: kong-database
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "8444:8444"
    
    konga-prepare:
        image: pantsel/konga
        container_name: konga-prepare
        command: "-c prepare -a postgres -u postgresql://kong:kong@kong-database:5432/konga"
        networks:
            - kong-net
        restart: on-failure
        links:
            - kong-database:kong-database
        depends_on:
            - kong-database
    
    konga:
        image: pantsel/konga
        container_name: konga
        restart: on-failure
        links:
            - kong-database:kong-database
        depends_on:
            - kong-database
        networks:
            - kong-net
        environment:
            DB_ADAPTER: postgres
            DB_HOST: kong-database
            DB_PORT: 5432
            DB_USER: kong
            DB_PASSWORD: kong
            DB_DATABASE: konga
            KONGA_HOOK_TIMEOUT: 120000
            NODE_ENV: production  
        ports:
            - "1337:1337"