version: "3"

networks:
    kong-net:
        name: kong-net
        driver: bridge
        
services:
 rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'
    networks:
            - kong-net 

volumes:
  rabbitmq_data: